#include <stdio.h>
#include <windows.h>
#include <stdlib.h>
#include <string.h>
#include <conio.h>
#include <time.h>
#include <ctime>
#include "Interface.h"
#include "Encript.h"
#include "FileManager.h"
